//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemittanceWindows.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrencyDenomination
    {
        public int CurrencyDenominationID { get; set; }
        public int LedgerID { get; set; }
        public byte CurrencyDenominationTypeID { get; set; }
        public short Quantity10000 { get; set; }
        public short Quantity1000 { get; set; }
        public short Quantity100 { get; set; }
        public short Quantity50 { get; set; }
        public short Quantity10 { get; set; }
        public short Quantity5 { get; set; }
        public short Quantity2 { get; set; }
        public decimal CoinAmount { get; set; }
    
        public virtual Ledger Ledger { get; set; }
    }
}
