//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemittanceWindows.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EC
    {
        public int ECID { get; set; }
        public int LedgerID { get; set; }
        public System.DateTime PurchaseDate { get; set; }
        public string Name { get; set; }
        public string ICNumber { get; set; }
        public string Telephone { get; set; }
        public string IDType { get; set; }
        public string Detail { get; set; }
        public string ReceivedDate { get; set; }
        public string Currency { get; set; }
        public decimal AmountForeignCurrency { get; set; }
        public decimal ExchangeRate { get; set; }
    
        public virtual Ledger Ledger { get; set; }
    }
}
