//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemittanceWindows.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ledger
    {
        public Ledger()
        {
            this.Cheques = new HashSet<Cheque>();
            this.CurrencyDenominations = new HashSet<CurrencyDenomination>();
            this.ECs = new HashSet<EC>();
            this.Pays = new HashSet<Pay>();
        }
    
        public int LedgerID { get; set; }
        public short UserID { get; set; }
        public System.DateTime Date { get; set; }
        public decimal ReportAmount { get; set; }
    
        public virtual ICollection<Cheque> Cheques { get; set; }
        public virtual ICollection<CurrencyDenomination> CurrencyDenominations { get; set; }
        public virtual ICollection<EC> ECs { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Pay> Pays { get; set; }
    }
}
