//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemittanceWindows.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RemittanceEntities : DbContext
    {
        public RemittanceEntities()
            : base("name=RemittanceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Cheque> Cheques { get; set; }
        public DbSet<CurrencyDenomination> CurrencyDenominations { get; set; }
        public DbSet<EC> ECs { get; set; }
        public DbSet<Ledger> Ledgers { get; set; }
        public DbSet<Pay> Pays { get; set; }
        public DbSet<User> Users { get; set; }
    }
}
