//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemittanceWindows.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Ledgers = new HashSet<Ledger>();
        }
    
        public short UserID { get; set; }
        public byte TeamID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Ledger> Ledgers { get; set; }
    }
}
